window.CVL_REFERENCE = {
  publicationPolicy: {
    label: "Public prototype evidence policy",
    scope: [
      "Use broadly accepted reference values, public population summaries, and public aggregate statistics as source-labeled engineering priors.",
      "Use published generalized equations only within their stated population and age range, with uncertainty and limitations preserved.",
      "Use treatment-oriented clinical papers only as plausibility checks; do not encode treatment values such as intubation depth.",
      "Run analysis and synthesis only on the user's PC through loopback-bound local services.",
    ],
    exclusions: [
      "Do not use case reports, individual patient rows, subject IDs, imaging files, or row-level clinical data.",
      "Do not infer, collect, cache, export, or link participant-level records from external dataset views.",
      "Do not present preview parameters as medical diagnosis, treatment advice, or individual biological identification.",
      "Do not collect or infer lifestyle history, disease history, inflammation, or airway narrowing in the public implementation.",
      "Do not use a real person's image without explicit consent or another lawful basis for use.",
    ],
    disclosure: "埋め込み値は、公開集計統計、一般化式、または明示された工学的近似に限定します。個人単位の臨床情報は使用せず、治療目的の数値は妥当性確認に限ります。解析・生成データはユーザーPC上でのみ処理されます。",
  },
  sources: {
    audioCpp2026: {
      label: "0xShug0/audio.cpp, local ggml audio inference runtime",
      url: "https://github.com/0xShug0/audio.cpp",
      use: "Local TTS runtime, persistent model server, and OpenAI-style speech endpoint used by the CharacterVoiceDesigner adapter.",
      privacy_note: "Software/runtime reference only. Character profiles and text are sent only to the user-operated loopback server.",
      evidence_level: "software_runtime_reference",
      publication_use: "implementation_dependency",
      public_release_status: "Apache-2.0; retain upstream notices",
    },
    irodoriTts600mV3VoiceDesign: {
      label: "Aratako, Irodori-TTS-600M-v3-VoiceDesign",
      url: "https://huggingface.co/Aratako/Irodori-TTS-600M-v3-VoiceDesign",
      use: "Initial Japanese caption-conditioned VoiceDesign model behind the audio.cpp adapter.",
      privacy_note: "Pretrained-model interface only. No source training records, reference-speaker audio, participant identifiers, or row-level data are imported into this project.",
      evidence_level: "pretrained_tts_model_reference",
      publication_use: "runtime_model_dependency",
      public_release_status: "MIT; model-card ethical restrictions apply, including no impersonation without explicit consent and no misleading synthetic speech",
    },
    worldVocoder2016: {
      label: "Morise et al. 2016, WORLD: a vocoder-based high-quality speech synthesis system",
      doi: "10.1587/transinf.2015EDP7457",
      url: "https://github.com/JeremyCCHsu/Python-Wrapper-for-World-Vocoder",
      use: "Optional post-TTS F0 analysis using DIO and StoneMask through pyworld. F0 transformation is performed separately with Praat PSOLA to avoid full vocoder resynthesis.",
      privacy_note: "Signal-processing method and software only. No participant recordings or row-level measurements are embedded.",
      evidence_level: "signal_processing_method_reference",
      publication_use: "implementation_dependency",
      public_release_status: "usable_with citation; pyworld is MIT licensed",
    },
    praatPsola2026: {
      label: "Boersma and Weenink, Praat / praat-parselmouth",
      url: "https://www.fon.hum.uva.nl/praat/",
      use: "Waveform-preserving overlap-add resynthesis for direct post-TTS F0 correction after WORLD measurement.",
      privacy_note: "Signal-processing software only. No participant recordings or row-level measurements are embedded.",
      evidence_level: "signal_processing_software_reference",
      publication_use: "implementation_dependency",
      public_release_status: "praat-parselmouth GPL-3.0-or-later; installed as an external runtime dependency and not incorporated into this repository's source",
    },
    pisanski2014: {
      label: "Pisanski et al. 2014, Vocal indicators of body size in men and women: a meta-analysis",
      doi: "10.1016/j.anbehav.2014.06.011",
      bundle_file: "01_Pisanski_2014_Vocal_indicators_of_body_size_meta_analysis.pdf",
      use: "Justifies weak/conservative body-to-voice mapping and range-based estimates.",
      publication_use: "formula_or_aggregate_reference",
      public_release_status: "usable_with_citation",
      extracted_values: {
        adult_height_weight_sample: {
          male: { height_cm_mean: 179.34, height_cm_sd: 7.16, weight_kg_mean: 74.96, weight_kg_sd: 12.44 },
          female: { height_cm_mean: 166.37, height_cm_sd: 6.93, weight_kg_mean: 63.28, weight_kg_sd: 10.77 },
          neutral: { height_cm_mean: 172.86, height_cm_sd: 7.05, weight_kg_mean: 69.12, weight_kg_sd: 11.61 },
        },
      },
    },
    pisanski2016: {
      label: "Pisanski et al. 2016, Voice parameters predict sex-specific body morphology in men and women",
      doi: "10.1016/j.anbehav.2015.11.008",
      bundle_file: "02_Pisanski_2016_Voice_parameters_and_body_morphology.pdf",
      use: "Provides adult sex-class voice priors used for preview synthesis and vocal-tract-length ranges.",
      publication_use: "formula_or_aggregate_reference",
      public_release_status: "usable_with_citation",
      extracted_values: {
        voice_table_1: {
          male: {
            f0_mean_hz: { mean: 114.16, sd: 17.01 },
            f1_hz: { mean: 466.61, sd: 45.92 },
            f2_hz: { mean: 1520.45, sd: 140.33 },
            f3_hz: { mean: 2592.49, sd: 132.29 },
            f4_hz: { mean: 3493.87, sd: 187.54 },
            vtl_fi_cm: { mean: 18.75, sd: 2.1 },
            vtl_df_cm: { mean: 17.35, sd: 0.79 },
          },
          female: {
            f0_mean_hz: { mean: 210.52, sd: 21.58 },
            f1_hz: { mean: 516.0, sd: 79.0 },
            f2_hz: { mean: 1848.0, sd: 200.0 },
            f3_hz: { mean: 3020.0, sd: 199.0 },
            f4_hz: { mean: 4100.0, sd: 217.0 },
            vtl_fi_cm: { mean: 15.61, sd: 1.63 },
            vtl_df_cm: { mean: 14.79, sd: 0.84 },
          },
          neutral: {
            f0_mean_hz: { mean: 162.34, sd: 19.3 },
            f1_hz: { mean: 491.31, sd: 62.46 },
            f2_hz: { mean: 1684.23, sd: 170.17 },
            f3_hz: { mean: 2806.25, sd: 165.65 },
            f4_hz: { mean: 3796.94, sd: 202.27 },
            vtl_fi_cm: { mean: 17.18, sd: 1.87 },
            vtl_df_cm: { mean: 16.07, sd: 0.82 },
          },
        },
      },
    },
    hiraharaAkahaneYamada2004JapaneseVowels: {
      label: "Hirahara and Akahane-Yamada 2004, Acoustic Characteristics of Japanese Vowels",
      url: "https://isd.pu-toyama.ac.jp/~auris/PDF/ICA2004-Th.P3.5.pdf",
      use: "Supports the Japanese-vowel profile scope and the use of aggregate F1-F4/B1-B4 acoustic measurements.",
      privacy_note: "Published aggregate acoustic analyses only. Source audio, token rows, and speaker-level measurements are not accessed or embedded.",
      evidence_level: "public_aggregate_phonetic_reference",
      publication_use: "aggregate_phonetic_scope_and_method_reference",
      public_release_status: "usable_with_citation",
    },
    kagomiya2015JapaneseVowelDuration: {
      label: "Kagomiya 2015, Articulatory positions of Japanese vowels as a function of duration computed from a large-scale spontaneous speech corpus",
      url: "https://www.internationalphoneticassociation.org/icphs-proceedings/ICPhS2015/Papers/ICPHS0671.pdf",
      use: "Provides the public sex-stratified aggregate F1/F2 centers used by the Japanese standard-vowel target profile. It also motivates treating Japanese /u/ as a centrally realized, weakly rounded target rather than importing a generic back-rounded /u/.",
      privacy_note: "Only the paper's published aggregate F1/F2 table is embedded. No corpus audio, token-level records, or speaker identifiers are collected, stored, linked, or exported.",
      evidence_level: "public_aggregate_phonetic_target",
      publication_use: "aggregate_phonetic_target_reference",
      public_release_status: "usable_with_scope_note",
      scope_note: "Adult Standard Japanese, spontaneous-speech aggregate target. It is a design target, not a diagnostic or speaker-identification model.",
    },
    mokhtariTanaka2000JapaneseFormantCorpus: {
      label: "Mokhtari and Tanaka 2000, A Corpus of Japanese Vowel Formant Patterns",
      url: "https://isd.pu-toyama.ac.jp/~parham/documents/formantsETL/2000_ETLBulletin_MokhtariTanaka.pdf",
      use: "Methodology and notation reference for Japanese vowel formant and bandwidth analysis; not used as a runtime numerical target.",
      privacy_note: "Citation/methodology only. The application does not embed the paper's speaker/frame/token measurements or any source recordings.",
      evidence_level: "phonetic_methodology_reference",
      publication_use: "citation_or_methodology_only",
      public_release_status: "usable_with_citation",
    },
    birkholz2013VocalTractLab: {
      label: "Birkholz 2013, Modeling Consonant-Vowel Coarticulation for Articulatory Speech Synthesis",
      doi: "10.1371/journal.pone.0060603",
      url: "https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0060603",
      use: "Method reference for separating vocal-tract geometry, articulatory time control, glottal excitation, and acoustic transmission-line simulation in an articulatory synthesizer.",
      privacy_note: "Method and model-architecture comparison only. VocalTractLab source code, speaker geometries, area functions, recordings, and fitted coefficients are not imported.",
      evidence_level: "public_articulatory_synthesis_method_reference",
      publication_use: "methodological_comparison_only",
      public_release_status: "usable_with_citation_and_no_subject_data",
    },
    dediu2022: {
      label: "Dediu et al. 2022, MRI vocal-tract structures in Dutch twins",
      doi: "10.1007/s00439-022-02469-2",
      bundle_file: "03_Dediu_2022_Heritability_of_vocal_tract_structures_MRI.pdf",
      use: "Supports keeping skull, face, mandible, hyoid/larynx, cervical and vocal-tract variables separate.",
      publication_use: "parameter_schema_support",
      public_release_status: "use_as_conceptual_support_only",
    },
    baer1991: {
      label: "Baer et al. 1991, Analysis of vocal tract shape and dimensions using MRI: vowels",
      doi: "10.1121/1.401949",
      url: "https://pubmed.ncbi.nlm.nih.gov/1939886/",
      use: "Supports deriving a cross-sectional area function from midsagittal dimensions; numeric subject-level mappings are not embedded.",
      publication_use: "methodological_support_only",
      public_release_status: "usable_with_citation_and_small_sample_warning",
      privacy_note: "The prototype uses the published method concept only, not participant images or subject-specific coefficients.",
    },
    kasess2012NasalTubeModel: {
      label: "Kasess et al. 2012, Estimation of the vocal tract shape of nasals using a Bayesian scheme",
      doi: "10.21437/Interspeech.2012-219",
      url: "https://www.isca-archive.org/interspeech_2012/kasess12_interspeech.html",
      use: "Method reference for representing nasal speech with connected pharyngeal, oral, and nasal tubes at the velar junction.",
      privacy_note: "Topology and continuity equations only. Recorded tokens, speaker-level estimates, and inferred tube areas are not embedded or used as runtime targets.",
      evidence_level: "public_acoustic_model_method_reference",
      publication_use: "methodological_support_only",
      public_release_status: "usable_with_citation_and_no_subject_data",
    },
    matsuzaki2014NasalCoupling: {
      label: "Matsuzaki et al. 2014, One-dimensional and three-dimensional propagation analyses of Japanese and French vowel /a/ with nasal coupling",
      doi: "10.1250/ast.35.35",
      url: "https://www.jstage.jst.go.jp/article/ast/35/1/35_E1282/_article",
      use: "Validity context for retaining a lightweight one-dimensional nasal-coupling model while explicitly documenting its higher-dimensional limitations.",
      privacy_note: "Published propagation-method comparison only. Subject-specific geometries, meshes, transfer functions, and imaging material are not imported.",
      evidence_level: "public_acoustic_validity_method_reference",
      publication_use: "validity_context_only",
      public_release_status: "usable_with_citation_and_no_subject_geometry",
    },
    rugchatjaroenHoward2017NasalWaveguide: {
      label: "Rugchatjaroen and Howard 2017, An evaluation of rectilinear digital waveguide mesh in modelling branch tube for English nasal synthesis",
      doi: "10.1016/j.apacoust.2017.02.002",
      url: "https://doi.org/10.1016/j.apacoust.2017.02.002",
      use: "Method reference for a multi-port waveguide junction that generates nasal resonances and oral-side-branch zeros without a separate post-hoc pole/zero filter.",
      privacy_note: "Waveguide topology only. No recorded speech, subject geometry, spectrogram, or fitted coefficient is embedded or used as a runtime target.",
      evidence_level: "public_acoustic_model_method_reference",
      publication_use: "methodological_support_only",
      public_release_status: "usable_with_citation_and_no_subject_data",
    },
    malecot1956NasalTransitions: {
      label: "Malecot 1956, Acoustic cues for nasal consonants",
      doi: "10.2307/411004",
      url: "https://doi.org/10.2307/411004",
      use: "Perceptual-method support for treating adjoining-vowel formant transitions as the principal /m/-/n/ place cue, while the nasal murmur primarily marks nasal manner.",
      privacy_note: "Generalized published experimental conclusion only. Recordings, participant responses, and token-level measurements are not imported.",
      evidence_level: "public_acoustic_perception_method_reference",
      publication_use: "methodological_support_only",
      public_release_status: "usable_with_citation_and_no_subject_data",
    },
    delattre1955AcousticLoci: {
      label: "Delattre, Liberman, and Cooper 1955, Acoustic loci and transitional cues for consonants",
      doi: "10.1121/1.1908024",
      url: "https://doi.org/10.1121/1.1908024",
      use: "Historical synthetic-speech basis for using a tract-length-scaled 1.8 kHz alveolar F2 locus as a regularized engineering prior at the release keyframe.",
      privacy_note: "The 1.8 kHz synthetic-speech locus is not represented as a biological, population, or individual norm.",
      evidence_level: "public_synthetic_speech_method_reference",
      publication_use: "engineering_prior_with_explicit_limitation",
      public_release_status: "usable_with_citation_and_no_subject_data",
    },
    haradaKawarada1987JapaneseNasals: {
      label: "Harada and Kawarada 1987, High resolution frequency analysis of Japanese nasal syllables",
      url: "https://tus.elsevierpure.com/en/publications/high-resolution-frequency-analysis-of-voices-feature-extraction-o/",
      use: "Japanese-language validity context that labial/alveolar nasal distinctions extend through the F2 transition and the interval between F2 and higher formants.",
      privacy_note: "Published aggregate conclusion only. Speaker recordings, per-speaker spectra, and fitted recognition coefficients are not imported.",
      evidence_level: "public_aggregate_acoustic_validity_reference",
      publication_use: "validity_context_only",
      public_release_status: "usable_with_citation_and_no_participant_data",
    },
    aistHql2003: {
      label: "AIST/HQL 3D Anthropometric Database 2003, public aggregate statistics",
      citation_label: "AIST/HQL 2003",
      url: "https://www.airc.aist.go.jp/dhrt/fbodydb/2003_Statistics.pdf",
      use: "Provides public aggregate median and SD for frontal neck-root breadth in young Japanese adults.",
      publication_use: "public_aggregate_anthropometric_prior",
      public_release_status: "usable_with_citation",
      privacy_note: "Aggregate table only; individual records are neither accessed nor embedded.",
      extracted_values: {
        neck_root_breadth_cm: {
          male: { n: 49, mean: 14.23, sd: 0.84, median: 14.15, age_mean: 24.6 },
          female: { n: 48, mean: 12.48, sd: 0.63, median: 12.38, age_mean: 27.5 },
          neutral: { n: 97, mean: 13.364, sd: 1.149, median: null, age_mean: 26.05, derived: true, derivation: "sample-size-weighted mean and pooled SD including between-sex-group variance" },
        },
      },
    },
    aistAnthropometryManual: {
      label: "AIST Human Body Dimensions Database 1991-92, anthropometry manual",
      citation_label: "AIST人体計測マニュアル",
      url: "https://www.airc.aist.go.jp/dhrt/91-92/fig/91-92_anthrop_manual.pdf",
      use: "Defines the canonical Japanese anatomical landmark names and cross-view measurement endpoints used by the WebUI.",
      publication_use: "terminology_and_measurement_definition",
      public_release_status: "usable_with_citation",
      privacy_note: "Definition manual only; no participant-level data is accessed or embedded.",
    },
    japaneseTracheaUhrct2023: {
      label: "Miyamoto et al. 2023, Japanese tracheal size and shape using ultra-high-resolution CT",
      citation_label: "Miyamoto et al. 2023",
      bundle_file: "超高精細CTを用いた日本人の気管の大きさと.pdf",
      use: "Plausibility check for adult tracheal transverse and anteroposterior design values; never used to infer a character from neck width.",
      publication_use: "clinical_aggregate_validity_check_only",
      public_release_status: "citation_only_no_embedded_patient_material",
      privacy_note: "Clinical images and row-level observations are excluded. Published aggregate summaries may only validate calculated ranges.",
    },
    honda2001: {
      label: "Honda 2001, Facial shape and voice quality",
      bundle_file: "04_Honda_2001_Facial_shape_and_voice_quality_JP.pdf",
      use: "Cautionary bridge: facial shape can constrain voice-related anatomy, but not as a one-to-one voice predictor.",
      publication_use: "validity_context",
      public_release_status: "use_as_conceptual_support_only",
    },
    sourceMap: {
      label: "DIMENSION_ESTIMATION_SOURCE_MAP.md",
      citation_label: "推定ソースマップ",
      bundle_file: "DIMENSION_ESTIMATION_SOURCE_MAP.md",
      use: "Defines which dimensions are image-priority and which are statistical-prior-priority in the MVP.",
      publication_use: "internal_design_document",
      public_release_status: "usable",
      display_in_reference_table: false,
    },
    pendingAist: {
      label: "AIST Japanese Head Dimensions Database 2001",
      citation_label: "AIST頭部寸法DB 2001",
      bundle_file: "DATASET_AND_SOURCE_LINKS.md only; numeric table not bundled",
      use: "Planned source for Japanese head and face priors. Not numerically embedded until the table is provided.",
      publication_use: "planned_public_reference_dataset",
      public_release_status: "pending_numeric_table_and_terms_check",
      display_in_reference_table: false,
    },
    localPdfGrowthPriors: {
      label: "Local PDF-derived Japanese growth and respiratory priors",
      citation_label: "PDF由来成長基準",
      local_cache: "local_pdf_growth_priors.js",
      use: "Provides manually extracted aggregate references for school-age head growth, pediatric sinus development, and young respiratory-function equations. Pediatric intubation papers are citation-only plausibility checks.",
      privacy_note: "Aggregate/manual-extract values only. No participant-level records.",
      evidence_level: "manual_extract",
      publication_use: "aggregate_prior_and_clinical_plausibility_check",
      public_release_status: "aggregate values usable with source scope; pediatric intubation values excluded",
    },
    yumigeta2019BodyFatDistribution: {
      label: "Yumigeta et al. 2019, Characteristics of body fat distribution based on somatotype in Japanese young women",
      doi: "10.3861/kenko.85.5_157",
      bundle_file: "日本人若年女性における体型からみた体脂肪分布の特徴.pdf",
      use: "Provides aggregate young-female BMI/body-fat somatotype groups and regional fat-distribution ratios for setting guidance.",
      privacy_note: "Published aggregate group summaries only. No participant-level records, images, or IDs are used.",
      evidence_level: "manual_extract_public_aggregate",
      publication_use: "aggregate_body_composition_setting_guide",
      public_release_status: "usable_with_scope_note",
    },
    deurenberg1991BodyFatFormula: {
      label: "Deurenberg et al. 1991, Body mass index as a measure of body fatness",
      doi: "10.1079/BJN19910073",
      use: "Formula-level fallback estimating body-fat percentage from BMI, age, and sex when direct age-band body-fat distributions are unavailable.",
      privacy_note: "Formula only; no participant-level records are embedded.",
      evidence_level: "formula_level_reference",
      publication_use: "formula_level_mapping_with_accuracy_warning",
      public_release_status: "usable_as_fallback_formula",
    },
    nchsAnthropometricReference2011_2014: {
      label: "NCHS/CDC Anthropometric Reference Data for Children and Adults: United States, 2011-2014",
      use: "Provides adult BMI percentile tables by sex and age band. Used only as a General-population fallback when a Japanese age-band BMI table is not loaded.",
      privacy_note: "Published aggregate percentile table only.",
      evidence_level: "public_aggregate_percentiles",
      publication_use: "general_population_fallback_reference",
      public_release_status: "usable_with_non_japanese_scope_note",
    },
    cdcNhanesBodyFatQuickStats1999_2004: {
      label: "CDC/NHANES 1999-2004 QuickStats, mean percentage body fat by age group and sex",
      use: "Scoping source indicating that body-fat percentage varies by age and sex in large public health surveys. Numeric table not fully embedded in this prototype.",
      privacy_note: "Published aggregate survey summary only.",
      evidence_level: "public_aggregate_scoping_reference",
      publication_use: "scoping_reference_only_until_primary_table_is_cached",
      public_release_status: "citation_or_scoping_only",
    },
    komiya1997JapaneseBodyComposition: {
      label: "Komiya 1997, Body Composition of Japanese Men and Women",
      doi: "10.15017/653",
      bundle_file: "日本人の体組成.pdf",
      use: "Provides manually extracted aggregate Japanese age/sex body-composition reference groups for BMI, body-fat percentage, fat mass, lean mass, and selected skinfold thickness.",
      privacy_note: "Published aggregate review/table values only. No participant-level records, images, or IDs are used.",
      evidence_level: "manual_extract_public_aggregate_review",
      publication_use: "aggregate_body_composition_setting_guide",
      public_release_status: "usable_with_method_warning",
      method_warning: "Underwater-weighing estimates and review-derived standard models are used as engineering centers, not as clinical norms or individual diagnosis.",
    },
    regionalSkinfoldThickness1996: {
      label: "Regional subcutaneous fat thickness distribution by percent body fat, 1996",
      citation_label: "部位別皮下脂肪厚 1996",
      bundle_file: "体脂肪率からみた部位別皮下脂肪厚の分布.pdf",
      use: "Provides aggregate sex-specific regional skinfold means and regression slopes per 1 percent body fat. Used only as a relative site-response guide.",
      privacy_note: "Published aggregate means/regression slopes only. No participant-level records, images, or IDs are used.",
      evidence_level: "manual_extract_public_aggregate_method_reference",
      publication_use: "regional_skinfold_response_guide_only",
      public_release_status: "usable_with_population_warning",
      population_warning: "The study sample is healthy white adults in the United States, ages 18-49. It is not used as a Japanese population center.",
    },
    utauOriginalSettingsGuide2008: {
      label: "Ameya/Ayame 2008, UTAU original-sample timing guide",
      url: "https://utau2008.blog47.fc2.com/blog-entry-39.html",
      use: "Implementation precedent for representing CV timing with preutterance/overlap anchors rather than treating the consonant and vowel as unrelated clips.",
      privacy_note: "Documentation and timing semantics only. No UTAU voicebank waveform is embedded, redistributed, or used as a runtime numerical target.",
      evidence_level: "software_method_reference",
      publication_use: "implementation_precedent_only",
      public_release_status: "usable_with_citation",
    },
  },

  phoneticTargetProfiles: {
    ja_JP_standard_neutral_aggregate_0_1: {
      label: "Japanese (Standard Japanese, neutral five-vowel target)",
      language: "ja-JP",
      speech_style: "neutral / spontaneous-speech aggregate",
      profile_scope: "A linguistic acoustic/articulatory target. It is independent of morphology_reference_population and must not be interpreted as an ancestry or ethnicity selector.",
      evidence_scope: "F1/F2 values are published adult sex-stratified aggregates. F3/F4 are an explicitly provisional engineering extension from public general sex-class baselines plus vowel-shape factors.",
      source_keys: ["kagomiya2015JapaneseVowelDuration", "hiraharaAkahaneYamada2004JapaneseVowels", "pisanski2016"],
      f1_f2_source: "kagomiya2015JapaneseVowelDuration",
      f3_f4_source: "pisanski2016 + engineering_vowel_shape_factors_0_1",
      reference_vtl_cm_by_sex: { male: 17.35, female: 14.79, neutral: 16.07 },
      vtl_normalization_source: "pisanski2016",
      higher_formant_fallback: {
        source: "pisanski2016",
        method: "public sex-class F3/F4 baselines multiplied by provisional vowel-shape factors; not a Japanese F3/F4 measurement table",
      },
      vowels: {
        a: {
          label: "/a/",
          f1_f2_hz_by_sex: { male: [612.705, 1425.653], female: [680.833, 1639.177], neutral: [646.769, 1532.415] },
          higher_formant_factors: [0.93, 0.96],
          bandwidths_hz: [100, 125, 210, 300],
          amplitude: 1,
          articulation: {
            jaw_opening_target: 0.9,
            oral_cavity_expansion_gain: 1.25,
            mandibular_release_gain: 1,
            oral_aperture_gain: 1,
            lip_rounding_target: 0.05,
            lip_compression_target: 0.04,
            mouth_spread_target: 0.58,
            cross_section: { lip_aperture_aspect_target: 1, tongue_groove_target: 0.03, lateral_channel_target: 0.02 },
            warps: [{ center: 0.38, width: 0.16, gain: 0.48 }, { center: 0.94, width: 0.09, gain: 1.05 }],
            acoustic_area_calibration: {
              schema_version: "aggregate_target_inverse_area_0.1",
              method: "deterministic smooth A(x) inverse-design fit",
              adaptive_target_assist: true,
              target_scope: "Standard Japanese aggregate F1/F2 plus provisional engineering F3/F4",
              source_keys: ["kagomiya2015JapaneseVowelDuration", "pisanski2016"],
              regularization: "seven fixed-position gains with smooth interpolation and a log-gain penalty",
              points: [
                { position: 0.08, gain: 1.11 },
                { position: 0.2, gain: 0.91 },
                { position: 0.34, gain: 1.71 },
                { position: 0.5, gain: 1.6 },
                { position: 0.66, gain: 0.775 },
                { position: 0.82, gain: 1 },
                { position: 0.94, gain: 0.84 },
              ],
              points_by_tube_count: {
                19: [
                  { position: 0.08, gain: 1.4097 },
                  { position: 0.2, gain: 0.7872 },
                  { position: 0.34, gain: 1.9665 },
                  { position: 0.5, gain: 1.704 },
                  { position: 0.66, gain: 0.6704 },
                  { position: 0.82, gain: 1.09 },
                  { position: 0.94, gain: 0.7056 },
                ],
              },
            },
          },
        },
        i: {
          label: "/i/",
          f1_f2_hz_by_sex: { male: [366.562, 1922.23], female: [375.423, 2143.303], neutral: [370.993, 2032.767] },
          higher_formant_factors: [1.14, 1.04],
          bandwidths_hz: [75, 135, 215, 310],
          amplitude: 0.84,
          articulation: {
            jaw_opening_target: 0.24,
            oral_cavity_expansion_gain: 1,
            mandibular_release_gain: 1,
            oral_aperture_gain: 1.05,
            lip_rounding_target: 0.02,
            lip_compression_target: 0.1,
            mouth_spread_target: 0.98,
            cross_section: { lip_aperture_aspect_target: 1.45, tongue_groove_target: 0.18, lateral_channel_target: 0.14 },
            tongue_dorsum_profile_gain: 1.04,
            labial_transverse_profile_gain: 0.72,
            transverse_mouth_center: 0.935,
            transverse_mouth_width: 0.065,
            tongue_warps: [{ center: 0.3, width: 0.2, gain: 2 }, { center: 0.72, width: 0.115, gain: 0.36 }],
            labial_warps: [{ center: 0.95, width: 0.08, gain: 0.88 }],
            warps: [{ center: 0.3, width: 0.2, gain: 2 }, { center: 0.72, width: 0.115, gain: 0.36 }, { center: 0.95, width: 0.08, gain: 0.88 }],
          },
        },
        u: {
          label: "/u/",
          f1_f2_hz_by_sex: { male: [388.399, 1498.385], female: [414.401, 1683.164], neutral: [401.4, 1590.775] },
          higher_formant_factors: [0.86, 0.96],
          bandwidths_hz: [85, 125, 215, 300],
          amplitude: 0.8,
          articulation: {
            jaw_opening_target: 0.16,
            oral_cavity_expansion_gain: 1.1,
            mandibular_release_gain: 1.04,
            oral_aperture_gain: 0.66,
            lip_rounding_target: 0.18,
            lip_compression_target: 0.84,
            mouth_spread_target: 0.28,
            cross_section: { lip_aperture_aspect_target: 0.72, tongue_groove_target: 0.08, lateral_channel_target: 0.06 },
            tongue_dorsum_profile_gain: 1.06,
            labial_transverse_profile_gain: 0.9,
            transverse_mouth_center: 0.94,
            transverse_mouth_width: 0.07,
            tongue_warps: [{ center: 0.21, width: 0.15, gain: 1.12 }, { center: 0.56, width: 0.15, gain: 0.55 }],
            labial_warps: [{ center: 0.92, width: 0.08, gain: 0.42 }],
            warps: [{ center: 0.21, width: 0.15, gain: 1.12 }, { center: 0.56, width: 0.15, gain: 0.55 }, { center: 0.92, width: 0.08, gain: 0.42 }],
          },
        },
        e: {
          label: "/e/",
          f1_f2_hz_by_sex: { male: [441.547, 1771.912], female: [476.031, 2107.474], neutral: [458.789, 1939.693] },
          higher_formant_factors: [1.02, 1],
          bandwidths_hz: [85, 135, 210, 300],
          amplitude: 0.92,
          articulation: {
            jaw_opening_target: 0.43,
            oral_cavity_expansion_gain: 1,
            mandibular_release_gain: 1,
            oral_aperture_gain: 1.02,
            lip_rounding_target: 0.05,
            lip_compression_target: 0.08,
            mouth_spread_target: 0.91,
            cross_section: { lip_aperture_aspect_target: 1.34, tongue_groove_target: 0.11, lateral_channel_target: 0.08 },
            tongue_dorsum_profile_gain: 0.92,
            labial_transverse_profile_gain: 1.08,
            transverse_mouth_center: 0.88,
            transverse_mouth_width: 0.12,
            tongue_warps: [{ center: 0.34, width: 0.18, gain: 1.22 }, { center: 0.67, width: 0.13, gain: 0.38 }],
            labial_warps: [{ center: 0.94, width: 0.09, gain: 0.9 }],
            warps: [{ center: 0.34, width: 0.18, gain: 1.22 }, { center: 0.67, width: 0.13, gain: 0.38 }, { center: 0.94, width: 0.09, gain: 0.9 }],
          },
        },
        o: {
          label: "/o/",
          f1_f2_hz_by_sex: { male: [436.36, 1216.104], female: [467.588, 1336.98], neutral: [451.974, 1276.542] },
          higher_formant_factors: [0.92, 0.96],
          bandwidths_hz: [90, 125, 205, 295],
          amplitude: 0.9,
          articulation: {
            jaw_opening_target: 0.68,
            oral_cavity_expansion_gain: 1.48,
            mandibular_release_gain: 1.04,
            oral_aperture_gain: 1.3,
            lip_rounding_target: 0.7,
            lip_compression_target: 0.26,
            mouth_spread_target: 0.5,
            cross_section: { lip_aperture_aspect_target: 0.84, tongue_groove_target: 0.04, lateral_channel_target: 0.04 },
            tongue_warps: [{ center: 0.2, width: 0.15, gain: 0.6 }, { center: 0.42, width: 0.16, gain: 0.4 }],
            labial_warps: [{ center: 0.95, width: 0.08, gain: 0.42 }],
            warps: [{ center: 0.2, width: 0.15, gain: 0.6 }, { center: 0.42, width: 0.16, gain: 0.4 }, { center: 0.95, width: 0.08, gain: 0.42 }],
          },
        },
      },
    },
    general_five_vowel_engineering_0_1: {
      label: "General five-vowel engineering comparison",
      language: "und",
      speech_style: "comparison only",
      profile_scope: "Language-neutral engineering comparison profile. It is not a population, ethnicity, or diagnostic model.",
      evidence_scope: "Retains the previous provisional five-vowel targets so users can compare the Japanese aggregate profile against the original engineering mapping.",
      source_keys: [],
      f1_f2_source: "engineering_general_0_1",
      f3_f4_source: "engineering_general_0_1",
      reference_vtl_cm_by_sex: { male: 17, female: 17, neutral: 17 },
      vowels: {
        a: { label: "/a/", formants_hz: [730, 1090, 2440, 3500], bandwidths_hz: [90, 110, 180, 290], amplitude: 1, articulation: { jaw_opening_target: 0.9, oral_cavity_expansion_gain: 1.25, mandibular_release_gain: 1, oral_aperture_gain: 1, lip_rounding_target: 0.05, lip_compression_target: 0.04, mouth_spread_target: 0.58, warps: [{ center: 0.38, width: 0.16, gain: 0.48 }, { center: 0.94, width: 0.09, gain: 1.05 }] } },
        i: { label: "/i/", formants_hz: [300, 2200, 3000, 3650], bandwidths_hz: [70, 130, 220, 310], amplitude: 0.82, articulation: { jaw_opening_target: 0.16, oral_cavity_expansion_gain: 1, mandibular_release_gain: 1, oral_aperture_gain: 1, lip_rounding_target: 0.02, lip_compression_target: 0.1, mouth_spread_target: 0.98, warps: [{ center: 0.3, width: 0.2, gain: 2 }, { center: 0.76, width: 0.1, gain: 0.012 }, { center: 0.95, width: 0.08, gain: 0.85 }] } },
        u: { label: "/u/", formants_hz: [350, 900, 2200, 3400], bandwidths_hz: [80, 120, 220, 300], amplitude: 0.78, articulation: { jaw_opening_target: 0.18, oral_cavity_expansion_gain: 1, mandibular_release_gain: 1, oral_aperture_gain: 1, lip_rounding_target: 0.95, lip_compression_target: 0.06, mouth_spread_target: 0.03, warps: [{ center: 0.2, width: 0.13, gain: 1.15 }, { center: 0.4, width: 0.15, gain: 0.22 }, { center: 0.94, width: 0.09, gain: 0.025 }] } },
        e: { label: "/e/", formants_hz: [500, 1900, 2600, 3500], bandwidths_hz: [80, 130, 200, 300], amplitude: 0.9, articulation: { jaw_opening_target: 0.45, oral_cavity_expansion_gain: 1, mandibular_release_gain: 1, oral_aperture_gain: 1, lip_rounding_target: 0.05, lip_compression_target: 0.08, mouth_spread_target: 0.82, warps: [{ center: 0.34, width: 0.17, gain: 1.45 }, { center: 0.72, width: 0.11, gain: 0.25 }, { center: 0.95, width: 0.08, gain: 0.88 }] } },
        o: { label: "/o/", formants_hz: [500, 1000, 2400, 3400], bandwidths_hz: [85, 120, 190, 295], amplitude: 0.88, articulation: { jaw_opening_target: 0.62, oral_cavity_expansion_gain: 1.42, mandibular_release_gain: 1, oral_aperture_gain: 1.25, lip_rounding_target: 0.78, lip_compression_target: 0.2, mouth_spread_target: 0.38, warps: [{ center: 0.2, width: 0.13, gain: 0.72 }, { center: 0.42, width: 0.15, gain: 0.52 }, { center: 0.965, width: 0.05, gain: 0.16 }] } },
      },
    },
  },

  bodyCompositionGuides: {
    general_adult_bmi_nhanes_2011_2014: {
      label: "General adult BMI percentile fallback",
      source: "nchsAnthropometricReference2011_2014",
      population: "United States, NHANES 2011-2014",
      age_min: 20,
      age_max: 120,
      unit: "kg/m2",
      scope_note: "General参照用の成人BMI中央値。日本人年齢階級表ではないため、Japanese public aggregate選択時は暫定補助値としてのみ表示。",
      percentile_50_by_age_band: {
        male: [
          { age_min: 20, age_max: 29, median: 25.5 },
          { age_min: 30, age_max: 39, median: 27.5 },
          { age_min: 40, age_max: 49, median: 28.5 },
          { age_min: 50, age_max: 59, median: 28.3 },
          { age_min: 60, age_max: 69, median: 28.0 },
          { age_min: 70, age_max: 79, median: 27.8 },
          { age_min: 80, age_max: 120, median: 26.3 },
        ],
        female: [
          { age_min: 20, age_max: 29, median: 25.6 },
          { age_min: 30, age_max: 39, median: 27.6 },
          { age_min: 40, age_max: 49, median: 28.1 },
          { age_min: 50, age_max: 59, median: 28.6 },
          { age_min: 60, age_max: 69, median: 28.9 },
          { age_min: 70, age_max: 79, median: 28.3 },
          { age_min: 80, age_max: 120, median: 26.1 },
        ],
      },
    },
    japanese_body_composition_komiya_1997: {
      label: "Japanese age/sex body-composition aggregate guide",
      source: "komiya1997JapaneseBodyComposition",
      population: "Japanese aggregate review/model",
      unit: "mixed",
      scope_note: "Manual aggregate extract from Komiya 1997. Values are means or model centers, not medians. Use as a public Japanese engineering prior when a stricter age-band median table is not available.",
      method_warning: "Do not present these values as clinical standards. Underwater-weighing method differences can shift estimated body-fat percentage.",
      groups: {
        male: [
          {
            id: "male_16_20",
            label: "male 16-20",
            age_min: 16,
            age_max: 20,
            age_center: 18.7,
            age_sd: 1.3,
            height_cm: { mean: 170.1, sd: 6.0 },
            weight_kg: { mean: 61.5, sd: 8.3 },
            bmi: { mean: 21.3, sd: 2.5 },
            body_fat_mass_kg: { mean: 14.7, sd: 4.2 },
            body_fat_percent: { mean: 23.9 },
            subcutaneous_fat_kg: { mean: 5.9, sd: 3.6, percent_of_body_weight: 9.6 },
            internal_fat_kg: { mean: 8.8, sd: 2.8, percent_of_body_weight: 14.3 },
            lean_body_mass_kg: { mean: 46.8, sd: 5.2 },
            lbm_to_fat_ratio: { mean: 3.18, sd: 0.86 },
            triceps_skinfold_mm: { mean: 10.2, sd: 4.2 },
            subscapular_skinfold_mm: { mean: 13.0, sd: 5.5 },
            waist_hip_ratio: { mean: 0.8, sd: 0.04 },
          },
          {
            id: "male_40_49",
            label: "male 40-49",
            age_min: 40,
            age_max: 49,
            age_center: 45.2,
            age_sd: 3.1,
            height_cm: { mean: 163.2, sd: 5.9 },
            weight_kg: { mean: 62.6, sd: 8.2 },
            bmi: { mean: 23.5, sd: 2.1 },
            body_fat_mass_kg: { mean: 17.2, sd: 4.7 },
            body_fat_percent: { mean: 27.5 },
            subcutaneous_fat_kg: { mean: 7.7, sd: 3.7, percent_of_body_weight: 12.3 },
            internal_fat_kg: { mean: 9.5, sd: 2.1, percent_of_body_weight: 15.2 },
            lean_body_mass_kg: { mean: 45.4, sd: 5.2 },
            lbm_to_fat_ratio: { mean: 2.64, sd: 0.69 },
            triceps_skinfold_mm: { mean: 10.2, sd: 3.4 },
            subscapular_skinfold_mm: { mean: 19.5, sd: 7.9 },
            waist_hip_ratio: { mean: 0.91, sd: 0.05 },
          },
          {
            id: "male_60_69",
            label: "male 60-69",
            age_min: 60,
            age_max: 69,
            age_center: 65.1,
            age_sd: 2.7,
            height_cm: { mean: 164.3, sd: 6.2 },
            weight_kg: { mean: 55.1, sd: 6.4 },
            bmi: { mean: 20.4, sd: 2.1 },
            body_fat_mass_kg: { mean: 13.7, sd: 3.6 },
            body_fat_percent: { mean: 24.9 },
            subcutaneous_fat_kg: { mean: 4.8, sd: 1.9, percent_of_body_weight: 8.7 },
            internal_fat_kg: { mean: 8.9, sd: 2.4, percent_of_body_weight: 16.2 },
            lean_body_mass_kg: { mean: 41.4, sd: 4.4 },
            lbm_to_fat_ratio: { mean: 3.02, sd: 0.81 },
            triceps_skinfold_mm: { mean: 7.5, sd: 1.9 },
            subscapular_skinfold_mm: { mean: 13.3, sd: 4.1 },
            waist_hip_ratio: { mean: 0.87, sd: 0.05 },
          },
        ],
        female: [
          {
            id: "female_16_20",
            label: "female 16-20",
            age_min: 16,
            age_max: 20,
            age_center: 18.2,
            age_sd: 0.5,
            height_cm: { mean: 157.7, sd: 3.6 },
            weight_kg: { mean: 50.5, sd: 7.8 },
            bmi: { mean: 20.3, sd: 3.0 },
            body_fat_mass_kg: { mean: 15.8, sd: 4.7 },
            body_fat_percent: { mean: 31.3 },
            subcutaneous_fat_kg: { mean: 8.0, sd: 3.3, percent_of_body_weight: 15.8 },
            internal_fat_kg: { mean: 7.8, sd: 2.0, percent_of_body_weight: 15.4 },
            lean_body_mass_kg: { mean: 34.7, sd: 4.1 },
            lbm_to_fat_ratio: { mean: 2.2, sd: 0.5 },
            triceps_skinfold_mm: { mean: 15.4, sd: 5.2 },
            subscapular_skinfold_mm: { mean: 15.7, sd: 6.3 },
            waist_hip_ratio: { mean: 0.77, sd: 0.04 },
          },
          {
            id: "female_40_49",
            label: "female 40-49",
            age_min: 40,
            age_max: 49,
            age_center: 45.5,
            age_sd: 3.1,
            height_cm: { mean: 153.5, sd: 3.4 },
            weight_kg: { mean: 58.2, sd: 7.6 },
            bmi: { mean: 24.7, sd: 3.1 },
            body_fat_mass_kg: { mean: 19.5, sd: 4.2 },
            body_fat_percent: { mean: 33.5 },
            subcutaneous_fat_kg: { mean: 10.6, sd: 3.3, percent_of_body_weight: 18.2 },
            internal_fat_kg: { mean: 8.9, sd: 2.8, percent_of_body_weight: 15.3 },
            lean_body_mass_kg: { mean: 38.7, sd: 4.7 },
            lbm_to_fat_ratio: { mean: 1.98, sd: 0.38 },
            triceps_skinfold_mm: { mean: 19.4, sd: 5.0 },
            subscapular_skinfold_mm: { mean: 24.1, sd: 7.4 },
            waist_hip_ratio: { mean: 0.87, sd: 0.09 },
          },
          {
            id: "female_60_69",
            label: "female 60-69",
            age_min: 60,
            age_max: 69,
            age_center: 67.0,
            age_sd: 4.3,
            height_cm: { mean: 150.2, sd: 3.1 },
            weight_kg: { mean: 48.0, sd: 8.5 },
            bmi: { mean: 21.3, sd: 3.5 },
            body_fat_mass_kg: { mean: 16.8, sd: 5.7 },
            body_fat_percent: { mean: 35.0 },
            subcutaneous_fat_kg: { mean: 7.0, sd: 3.6, percent_of_body_weight: 14.6 },
            internal_fat_kg: { mean: 9.8, sd: 2.7, percent_of_body_weight: 20.4 },
            lean_body_mass_kg: { mean: 31.2, sd: 3.3 },
            lbm_to_fat_ratio: { mean: 1.86, sd: 0.48 },
            triceps_skinfold_mm: { mean: 14.2, sd: 4.7 },
            subscapular_skinfold_mm: { mean: 16.9, sd: 6.5 },
            waist_hip_ratio: { mean: 0.86, sd: 0.12 },
          },
        ],
      },
    },
    regional_skinfold_response_1996: {
      label: "Regional skinfold response per body-fat percentage",
      source: "regionalSkinfoldThickness1996",
      population: "healthy white adults in the United States, ages 18-49",
      unit: "mm",
      scope_note: "Used as a relative site-response guide only. The sample is not Japanese and does not define a Japanese body-composition center.",
      mean_body_fat_percent: {
        male: { mean: 11.7, sd: 4.1 },
        female: { mean: 21.4, sd: 5.3 },
      },
      sites: {
        male: {
          abdomen: { label: "abdomen", mean_mm: 7.3, sd_mm: 3.0, slope_mm_per_body_fat_percent: 0.449 },
          suprailiac: { label: "suprailiac", mean_mm: 6.1, sd_mm: 2.2, slope_mm_per_body_fat_percent: 0.339 },
          subscapular: { label: "subscapular", mean_mm: 5.8, sd_mm: 1.3, slope_mm_per_body_fat_percent: 0.16 },
          anterior_thigh: { label: "anterior thigh", mean_mm: 5.6, sd_mm: 1.6, slope_mm_per_body_fat_percent: 0.161 },
          biceps: { label: "biceps", mean_mm: 3.4, sd_mm: 0.7, slope_mm_per_body_fat_percent: 0.093 },
          triceps: { label: "triceps", mean_mm: 5.1, sd_mm: 1.3, slope_mm_per_body_fat_percent: 0.117 },
        },
        female: {
          abdomen: { label: "abdomen", mean_mm: 11.5, sd_mm: 6.4, slope_mm_per_body_fat_percent: 0.826 },
          suprailiac: { label: "suprailiac", mean_mm: 7.5, sd_mm: 2.9, slope_mm_per_body_fat_percent: 0.4 },
          subscapular: { label: "subscapular", mean_mm: 6.8, sd_mm: 2.0, slope_mm_per_body_fat_percent: 0.241 },
          anterior_thigh: { label: "anterior thigh", mean_mm: 10.5, sd_mm: 3.0, slope_mm_per_body_fat_percent: 0.382 },
          biceps: { label: "biceps", mean_mm: 4.7, sd_mm: 1.1, slope_mm_per_body_fat_percent: 0.133 },
          triceps: { label: "triceps", mean_mm: 8.2, sd_mm: 2.7, slope_mm_per_body_fat_percent: 0.317 },
        },
      },
    },
    deurenberg_body_fat_formula: {
      label: "BMI・年齢・性別に基づく体脂肪率推定式",
      source: "deurenberg1991BodyFatFormula",
      unit: "%",
      scope_note: "直接測定値や分布中央値ではなく、BMIから体脂肪率を推定する文献式。体型デザインの仮置きガイドに限って使用する。",
      adult_formula: "BF% = 1.20 * BMI + 0.23 * age - 10.8 * sex - 5.4",
      child_formula: "BF% = 1.51 * BMI - 0.70 * age - 3.6 * sex + 1.4",
      sex_code: "female=0, male=1, neutral=0.5",
    },
    young_japanese_female_bia_18_19: {
      label: "日本人若年女性 BIA 体脂肪分布ガイド",
      source: "yumigeta2019BodyFatDistribution",
      sex: "female",
      age_band_label: "18歳前後",
      age_min: 17,
      age_max: 20,
      sample_note: "女子大学生300名。全寮制・医療系学部の単一集団であり、一般人口の年齢階級中央値ではない。",
      measurement_method: "BIA, TANITA MC-190",
      bmi_median_proxy: 20.6,
      bmi_median_proxy_basis: "BMI昇順に並べた群別人数の累積中央値が隠れ肥満予備群に入るため、同群平均BMIを grouped median proxy として表示。",
      body_fat_percent_median_proxy: 27.3,
      body_fat_percent_median_proxy_basis: "同じ累積中央値群の平均体脂肪率。厳密な個票中央値ではない。",
      applicability_note: "女性・18歳前後のキャラクター設定で、体脂肪率と体脂肪分布の整合性を見るための補助ガイド。",
      groups: [
        {
          id: "low_weight",
          label: "やせ群",
          n: 17,
          criteria: "BMI < 18.5 / 体脂肪率 < 20%",
          bmi: { mean: 16.9, sd: 1.1 },
          body_fat_percent: { mean: 17.2, sd: 2.0 },
          upper_lower_fat_ratio: { mean: 1.5, sd: 0.4 },
          regional_percent: { arm: 5.9, leg: 59.9, trunk: 34.2 },
          interpretation: "下半身寄りの脂肪分布。体幹脂肪比は低い。",
        },
        {
          id: "sham_low_weight",
          label: "みせかけやせ群",
          n: 32,
          criteria: "BMI < 18.5 / 20% <= 体脂肪率 < 25%",
          bmi: { mean: 17.6, sd: 0.7 },
          body_fat_percent: { mean: 22.1, sd: 1.5 },
          upper_lower_fat_ratio: { mean: 1.1, sd: 0.1 },
          regional_percent: { arm: 6.2, leg: 51.4, trunk: 42.4 },
          interpretation: "BMIは低いが脂肪率は普通域。下半身寄りから均衡へ近づく。",
        },
        {
          id: "normal",
          label: "普通群",
          n: 48,
          criteria: "18.5 <= BMI < 25 / 20% <= 体脂肪率 < 25%",
          bmi: { mean: 19.4, sd: 0.6 },
          body_fat_percent: { mean: 23.3, sd: 1.2 },
          upper_lower_fat_ratio: { mean: 1.0, sd: 0.1 },
          regional_percent: { arm: 6.9, leg: 49.2, trunk: 43.9 },
          interpretation: "上半身・下半身の脂肪量がほぼ均衡する基準群。",
        },
        {
          id: "pre_masked_obesity",
          label: "隠れ肥満予備群",
          n: 137,
          criteria: "BMI < 25 / 25% <= 体脂肪率 < 30%",
          bmi: { mean: 20.6, sd: 1.2 },
          body_fat_percent: { mean: 27.3, sd: 1.4 },
          upper_lower_fat_ratio: { mean: 0.8, sd: 0.1 },
          regional_percent: { arm: 7.2, leg: 44.9, trunk: 47.8 },
          interpretation: "BMIは普通域でも体幹側へ脂肪分布が寄り始める。",
        },
        {
          id: "masked_obesity",
          label: "隠れ肥満群",
          n: 55,
          criteria: "18.5 <= BMI < 25 / 体脂肪率 >= 30%",
          bmi: { mean: 22.8, sd: 1.1 },
          body_fat_percent: { mean: 31.9, sd: 1.4 },
          upper_lower_fat_ratio: { mean: 0.7, sd: 0.1 },
          regional_percent: { arm: 7.7, leg: 40.8, trunk: 51.5 },
          interpretation: "BMIは普通域でも体脂肪分布は肥満群に近い。",
        },
        {
          id: "obesity",
          label: "肥満群",
          n: 11,
          criteria: "BMI >= 25 / 体脂肪率 >= 30%",
          bmi: { mean: 26.5, sd: 1.0 },
          body_fat_percent: { mean: 36.8, sd: 1.9 },
          upper_lower_fat_ratio: { mean: 0.6, sd: 0.1 },
          regional_percent: { arm: 8.6, leg: 38.3, trunk: 53.1 },
          interpretation: "体幹部の脂肪割合が高く、下肢割合が低い。",
        },
      ],
      age_band_research_targets: [
        "国民健康・栄養調査などの公開集計から、年齢階級別BMI中央値・分布を確認する。",
        "体脂肪率は測定法依存性が大きいため、BIA・DXA・皮下脂肪厚・CT/MRIを同じ尺度として混ぜない。",
        "女性では閉経前後で分布が変わるため、若年・中年・高年を別ガイドとして管理する。",
        "体幹部/下肢/腕部の割合は、総体脂肪率とは別の分布パラメータとして扱う。",
      ],
    },
  },

  anthropometricFeaturePriors: {
    shoulder_width_cm: {
      label: "肩峰幅",
      unit: "cm",
      mean: { female: 36, male: 42, neutral: 39 },
      sd: 3.2,
      source: "temporary_design_prior",
      source_note: "Direct shoulder-breadth cohort table is not bundled; replace with selected anthropometric dataset.",
      evidence: "pendingAist",
      evidence_level: "placeholder",
    },
    torso_length_cm: {
      label: "肩峰－転子外突垂直長（設計）",
      unit: "cm",
      mean: { female: 50, male: 56, neutral: 53 },
      sd: 4.5,
      source: "temporary_design_prior",
      source_note: "Direct torso-length cohort table is not bundled; used only for UI/pipeline validation.",
      evidence: "sourceMap",
      evidence_level: "placeholder",
    },
    pelvis_width_cm: {
      label: "大転子間幅",
      unit: "cm",
      mean: { female: 32, male: 31, neutral: 31.5 },
      sd: 3.1,
      source: "temporary_design_prior",
      source_note: "Direct pelvis-width cohort table is not bundled; used only as a low-confidence body-scale proxy.",
      evidence: "sourceMap",
      evidence_level: "placeholder",
    },
    head_units: {
      label: "頭身比（身長／全頭高）",
      unit: "ratio",
      mean: { female: 7.1, male: 7.4, neutral: 7.25 },
      sd: 0.55,
      source: "character_design_prior",
      source_note: "Character-art proportion control, not an anatomical population statistic.",
      evidence: "sourceMap",
      evidence_level: "design_proxy",
    },
    lower_face_height_cm: {
      label: "鼻下・オトガイ高",
      unit: "cm",
      mean: { female: 6.1, male: 6.8, neutral: 6.45 },
      sd: 0.55,
      source: "temporary_head_face_prior",
      source_note: "AIST is the intended Japanese source, but its numeric table is not bundled here.",
      evidence: "pendingAist",
      evidence_level: "placeholder",
    },
    mouth_width_cm: {
      label: "口裂幅（口角点間）",
      unit: "cm",
      mean: { female: 4.6, male: 5.1, neutral: 4.85 },
      sd: 0.45,
      source: "temporary_head_face_prior",
      source_note: "AIST is the intended Japanese source, but its numeric table is not bundled here.",
      evidence: "pendingAist",
      evidence_level: "placeholder",
    },
    interpupillary_width_cm: {
      label: "瞳孔間幅",
      unit: "cm",
      mean: { female: 6.1, male: 6.4, neutral: 6.25 },
      sd: 0.35,
      source: "temporary_head_face_prior",
      source_note: "Used as a face-image scale anchor until an optometry/head-dimension table is supplied.",
      evidence: "pendingAist",
      evidence_level: "placeholder",
    },
    jaw_width_cm: {
      label: "下顎角幅（顎角点間）",
      unit: "cm",
      mean: { female: 10.4, male: 11.8, neutral: 11.1 },
      sd: 1.0,
      source: "temporary_head_face_prior",
      source_note: "Dediu supports separating mandible variables; numeric Japanese prior is not bundled.",
      evidence: "dediu2022",
      evidence_level: "schema_supported_placeholder",
    },
    neck_root_width_cm: {
      label: "頸付根幅",
      unit: "cm",
      reference_population: "Japanese_public_aggregate",
      general_uncertainty_multiplier: 2,
      mean: { female: 12.48, male: 14.23, neutral: 13.364 },
      median: { female: 12.38, male: 14.15, neutral: 13.364 },
      median_source: { female: "source_table", male: "source_table", neutral: "derived_combined_mean_proxy" },
      sd: { female: 0.63, male: 0.84, neutral: 1.149 },
      source: "AIST/HQL 3D Anthropometric Database 2003 public aggregate table",
      source_note: "Young-adult Japanese aggregate. Outside the source age range, retain the value as a weak prior and widen uncertainty rather than extrapolating a trend.",
      evidence: "aistHql2003",
      evidence_level: "public_aggregate",
    },
  },
};
