window.CVL_REFERENCE = {
  sources: {
    pisanski2014: {
      label: "Pisanski et al. 2014, Vocal indicators of body size in men and women: a meta-analysis",
      bundle_file: "01_Pisanski_2014_Vocal_indicators_of_body_size_meta_analysis.pdf",
      use: "Justifies weak/conservative body-to-voice mapping and range-based estimates.",
      extracted_values: {
        adult_height_weight_sample: {
          male: { height_cm_mean: 179.34, height_cm_sd: 7.16, weight_kg_mean: 74.96, weight_kg_sd: 12.44 },
          female: { height_cm_mean: 166.37, height_cm_sd: 6.93, weight_kg_mean: 63.28, weight_kg_sd: 10.77 },
          neutral: { height_cm_mean: 172.86, height_cm_sd: 7.05, weight_kg_mean: 69.12, weight_kg_sd: 11.61 },
        },
      },
    },
    pisanski2016: {
      label: "Pisanski et al. 2016, Voice parameters predict sex-specific body morphology in men and women",
      bundle_file: "02_Pisanski_2016_Voice_parameters_and_body_morphology.pdf",
      use: "Provides adult sex-class voice priors used for preview synthesis and vocal-tract-length ranges.",
      extracted_values: {
        voice_table_1: {
          male: {
            f0_mean_hz: { mean: 114.16, sd: 17.01 },
            f1_hz: { mean: 466.61, sd: 45.92 },
            f2_hz: { mean: 1520.45, sd: 140.33 },
            f3_hz: { mean: 2592.49, sd: 132.29 },
            f4_hz: { mean: 3493.87, sd: 187.54 },
            vtl_fi_cm: { mean: 18.75, sd: 2.1 },
            vtl_df_cm: { mean: 17.35, sd: 0.79 },
          },
          female: {
            f0_mean_hz: { mean: 210.52, sd: 21.58 },
            f1_hz: { mean: 516.0, sd: 79.0 },
            f2_hz: { mean: 1848.0, sd: 200.0 },
            f3_hz: { mean: 3020.0, sd: 199.0 },
            f4_hz: { mean: 4100.0, sd: 217.0 },
            vtl_fi_cm: { mean: 15.61, sd: 1.63 },
            vtl_df_cm: { mean: 14.79, sd: 0.84 },
          },
          neutral: {
            f0_mean_hz: { mean: 162.34, sd: 19.3 },
            f1_hz: { mean: 491.31, sd: 62.46 },
            f2_hz: { mean: 1684.23, sd: 170.17 },
            f3_hz: { mean: 2806.25, sd: 165.65 },
            f4_hz: { mean: 3796.94, sd: 202.27 },
            vtl_fi_cm: { mean: 17.18, sd: 1.87 },
            vtl_df_cm: { mean: 16.07, sd: 0.82 },
          },
        },
      },
    },
    dediu2022: {
      label: "Dediu et al. 2022, MRI vocal-tract structures in Dutch twins",
      bundle_file: "03_Dediu_2022_Heritability_of_vocal_tract_structures_MRI.pdf",
      use: "Supports keeping skull, face, mandible, hyoid/larynx, cervical and vocal-tract variables separate.",
    },
    honda2001: {
      label: "Honda 2001, Facial shape and voice quality",
      bundle_file: "04_Honda_2001_Facial_shape_and_voice_quality_JP.pdf",
      use: "Cautionary bridge: facial shape can constrain voice-related anatomy, but not as a one-to-one voice predictor.",
    },
    sourceMap: {
      label: "DIMENSION_ESTIMATION_SOURCE_MAP.md",
      bundle_file: "DIMENSION_ESTIMATION_SOURCE_MAP.md",
      use: "Defines which dimensions are image-priority and which are statistical-prior-priority in the MVP.",
    },
    pendingAist: {
      label: "AIST Japanese Head Dimensions Database 2001",
      bundle_file: "DATASET_AND_SOURCE_LINKS.md only; numeric table not bundled",
      use: "Planned source for Japanese head and face priors. Not numerically embedded until the table is provided.",
    },
  },

  anthropometricFeaturePriors: {
    shoulder_width_cm: {
      label: "肩幅",
      unit: "cm",
      mean: { female: 36, male: 42, neutral: 39 },
      sd: 3.2,
      source: "temporary_design_prior",
      source_note: "Direct shoulder-breadth cohort table is not bundled; replace with selected anthropometric dataset.",
      evidence: "pendingAist",
      evidence_level: "placeholder",
    },
    torso_length_cm: {
      label: "胴体長",
      unit: "cm",
      mean: { female: 50, male: 56, neutral: 53 },
      sd: 4.5,
      source: "temporary_design_prior",
      source_note: "Direct torso-length cohort table is not bundled; used only for UI/pipeline validation.",
      evidence: "sourceMap",
      evidence_level: "placeholder",
    },
    pelvis_width_cm: {
      label: "骨盤幅",
      unit: "cm",
      mean: { female: 32, male: 31, neutral: 31.5 },
      sd: 3.1,
      source: "temporary_design_prior",
      source_note: "Direct pelvis-width cohort table is not bundled; used only as a low-confidence body-scale proxy.",
      evidence: "sourceMap",
      evidence_level: "placeholder",
    },
    head_units: {
      label: "頭身",
      unit: "ratio",
      mean: { female: 7.1, male: 7.4, neutral: 7.25 },
      sd: 0.55,
      source: "character_design_prior",
      source_note: "Character-art proportion control, not an anatomical population statistic.",
      evidence: "sourceMap",
      evidence_level: "design_proxy",
    },
    lower_face_height_cm: {
      label: "顔面下部長",
      unit: "cm",
      mean: { female: 6.1, male: 6.8, neutral: 6.45 },
      sd: 0.55,
      source: "temporary_head_face_prior",
      source_note: "AIST is the intended Japanese source, but its numeric table is not bundled here.",
      evidence: "pendingAist",
      evidence_level: "placeholder",
    },
    mouth_width_cm: {
      label: "口裂幅",
      unit: "cm",
      mean: { female: 4.6, male: 5.1, neutral: 4.85 },
      sd: 0.45,
      source: "temporary_head_face_prior",
      source_note: "AIST is the intended Japanese source, but its numeric table is not bundled here.",
      evidence: "pendingAist",
      evidence_level: "placeholder",
    },
    interpupillary_width_cm: {
      label: "瞳孔間距離",
      unit: "cm",
      mean: { female: 6.1, male: 6.4, neutral: 6.25 },
      sd: 0.35,
      source: "temporary_head_face_prior",
      source_note: "Used as a face-image scale anchor until an optometry/head-dimension table is supplied.",
      evidence: "pendingAist",
      evidence_level: "placeholder",
    },
    jaw_width_cm: {
      label: "下顎角幅",
      unit: "cm",
      mean: { female: 10.4, male: 11.8, neutral: 11.1 },
      sd: 1.0,
      source: "temporary_head_face_prior",
      source_note: "Dediu supports separating mandible variables; numeric Japanese prior is not bundled.",
      evidence: "dediu2022",
      evidence_level: "schema_supported_placeholder",
    },
  },
};
